---
title: "LAB EXERCISE - 6 SVM"
author: "KANDULA NAVEEN KUMAR - 17MIS1056"
date: "16/03/2021"
output: word_document
---

```{r}
library(e1071)
library(dplyr)
library(ggplot2)
library(caret)
```


```{r}
library(nnet)
```


```{r}
setwd("D:\\8TH SEM")
train<- read.csv("titanic_train.csv")
test<-read.csv("titanic_test.csv")
```


```{r}
train<-train[,-c(1,3,8,10,12,13,14)]
any(is.na(train))
```


```{r}
summary(train)
```


```{r}
head(train)
```



```{r}
str(train)
```


```{r}
glimpse(train)
```


```{r}
train$survived = factor(train$survived, levels = c(0, 1))
train$sex = factor(train$sex,levels = c('male', 'female'),labels = c(1, 2))
train$embarked = factor(train$embarked,levels = c('C', 'Q', 'S'),labels = c(1, 2, 3))
train$pclass = factor(train$pclass, levels = c(1, 2, 3))
```


```{r}
summary(train)
```

#Handling th missing data with the mean of the feature and train-test split.

```{r}
train$age = ifelse(is.na(train$age),ave(train$age, FUN = function(x) mean(x, na.rm = TRUE)),train$age)
head(train)

```


```{r}
library(caTools)
set.seed(123)
index<-sample.split(train$survived,SplitRatio =  0.8)
train1<-subset(train,index==TRUE)
test1<-subset(train,index==FALSE)

```


```{r}
svmfit=svm(survived~ . ,data = train1,kernel = "linear")
svmfit
```


```{r}
y_pred = predict(svmfit, newdata = test1)
```


```{r}
confusionMatrix(test1$survived,y_pred)
```


```{r}
svmfit=svm(survived~ . ,data = train1,kernel = "radial")
svmfit
```


```{r}
y_pred = predict(svmfit, newdata = test1)
#plot(svmfit, train1)
confusionMatrix(test1$survived,y_pred)
```

#Polynomial Kernel

```{r}
svmfit=svm(survived~ . ,data = train1,kernel = "polynomial")
svmfit
```

```{r}
y_pred = predict(svmfit, newdata = test1)
#plot(svmfit, train1)
confusionMatrix(test1$survived,y_pred)
```

```{r}
folds = createFolds(train$survived, k = 5)
tuned = tune.svm(survived~., data = train,kernel='polynomial')
summary(tuned)
```

```{r}
y_pred1=predict(tuned$best.model, newdata = test1)
confusionMatrix(test1$survived,y_pred1)
```

# Cross fold validation for polynomial Kernel

```{r}
folds = createFolds(train$survived, k = 5)
tuned = tune.svm(survived~., data = train,kernel='radial')
summary(tuned)
```


```{r}
y_pred1=predict(tuned$best.model, newdata = test1)
confusionMatrix(test1$survived,y_pred1)
```

#linear in the previous no cross validation has seen less accuracy then compared with that of the k-cross validation technique.




